### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by cwlfw** [reinhardfuehricht/typo3-formhandler#18]
Thanks for the great formhandler-extension. On typo3 7.10, formhandler version 2.3.1 and on this version 2.4.0 dev the following error Handling shows up:
When filling out the form and sending a simple form the error Handling: "Ein Fehler ist aufgetreten" is shown. 
When using the same form with an incorrect e-mail address like: something@
the form is correctly not send and the error message is shown. After correcting the email-field to 
something@webbb.de
this form is send correct and everything works great. It seems that the form always works when a browser error message was produced in advanced.  
The same examples are working fine in typo3.6.2 formhandler version 2.0.2 
Maybe you have a short note about this. 
I hope this is the right place to address this issue.
Best wishes fw

**Comment by reinhardfuehricht** [comment]
Hi!

Please turn on the debug mode using "debug=1" in your Formhandler-TypoScript. Then you should see the full stack trace of the error, which should help you finding out what's causing the problem.

**Comment by cwlfw** [comment]
Hi,
trying to send the form shows now:
Typoheads\Formhandler\Controller\Form
Aktueller Step: 2
Höchster Subparts im Template (Anzahl der Steps): 1
Verwende Prefix für Formularwerte: "newsletter"
Verwende View "Typoheads\Formhandler\View\Form"
Die aktuellen GET/POST-Parameter:
array(8 items)
   submitted => '1' (1 chars)
   randomID => '93fe12a301ad23f45ca577e5393cac3b' (32 chars)
   removeFile => '' (0 chars)
   removeFileField => '' (0 chars)
   submitField => '' (0 chars)
   step-2-next => 'Register' (8 chars)
   name => 'Testname' (8 chars)
   email => 'something@webbb.de' (18 chars)
Leere Parameter in der Session
Aktueller Step: 2
Die aktuellen Werte in der Session:
Rufe Klasse "Typoheads\Formhandler\Interceptor\RemoveXSS" auf!
Files:
Typoheads\Formhandler\Validator\DefaultValidator
Rufe Klasse "Typoheads\Formhandler\Validator\ErrorCheck\Required" auf!
Rufe Klasse "Typoheads\Formhandler\Validator\ErrorCheck\Required" auf!
Rufe Klasse "Typoheads\Formhandler\Validator\ErrorCheck\Email" auf!
Rufe Klasse "Typoheads\Formhandler\Validator\ErrorCheck\IsNotInDBTable" auf!

Many thanks!

**Comment by reinhardfuehricht** [comment]
And what about the "An error occurred" message? There should be a quite huge red text block on your website showing an error message.

**Comment by cwlfw** [comment]
Hi, 
there is no error massage, when I use 
debug=1
When I open the formpage I see:
Typoheads\Formhandler\Controller\Form
Aktueller Step: 1
Höchster Subparts im Template (Anzahl der Steps): 1
Verwende Prefix für Formularwerte: "newsletter"
Verwende View "Typoheads\Formhandler\View\Form"
Die aktuellen GET/POST-Parameter:
Leere Parameter in der Session
Die aktuellen Werte in der Session:
Verwende Subpart "###TEMPLATE_FORM1###"!
Rufe Klasse "Typoheads\Formhandler\PreProcessor\LoadGetPost" auf!
Rufe Klasse "Typoheads\Formhandler\PreProcessor\ValidateAuthCode" auf!
Rufe Klasse "Typoheads\Formhandler\Interceptor\RemoveXSS" auf!

After filling out the form the above comment is displayed, starting with 
Typoheads\Formhandler\Controller\Form
Aktueller Step: 2
....
Here is the link:
https://www.tp764.cwl24.com/index.php?id=120
When calling the link I realize, the link starts with https:/....  and for the subdomains I have no https certificate. Could this be the reason for this behavior?

Many thanks!

**Comment by reinhardfuehricht** [comment]
OK, first of all, where is your submit button? I don't see any and I can't submit the form, when hitting return in a field.
Then, the missing certificate could indeed be a problem. The URL you sent me uses www.domain.tld, but your base URL says only domain.tld.

**Comment by cwlfw** [comment]
Hi, 
there is a strange behavior about the submit-botton. If I'm logged-in the backend, the submit-botton is shown (in the same browser as I'm logged in). As normal Webpage-User no submit-booton is there. It seems to me, the master submit-part is not loaded. So I try to check on this problem. 
In the meantime many thanks!

**Comment by cwlfw** [comment]
Hi, 
I have probably made the following mistakes:
First: when using debug=1 and preProcessors ...   the submit-botton is not shown if someone is not logged in the backend. 
Second: My baseUrl was also wrong. For this subdomain now works
baseUrl = www.subdomain.domain.tld  (no https://)
formhandler works fine now. 
Many thanks for your help and best wishes!
