### ISSUE TITLE
Tx_Formhandler_Finisher_GenerateAuthCode broken since last TYPO3 security fix

### ISSUE THREAD

**Issue by ilomedia** [reinhardfuehricht/typo3-formhandler#20]
Since i updated TYPO3 due to the following security flaw authcode does not work anymore : https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2016-022/

Clicking the link results in the following error though authCodePage is set :

> ID parameter needs to be passed for the cHash calculation! As a temporary not recommended workaround, you can set $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] to false to avoid this error.

**Comment by reinhardfuehricht** [comment]
Did you update EXT:realurl too?

The link to the auth code page is generated using the typolink method of the core, so I don't think that the security update requires any changes in Formhandler.

**Comment by ilomedia** [comment]
[feeling stupid]
after a dozen of print_r i realized that i had a trailing &uid=1 after ###value_authCodeUrl### (copy/paste inferno)
[feeling stupid]
