### ISSUE TITLE
Using formhandler with flexform values doesn't work

### ISSUE THREAD

**Issue by pserrer** [reinhardfuehricht/typo3-formhandler#6]
If I define a recipient in the backend flexform for formhandler, I got the error message missing_component (Missing finishers! The Flexform contains 'mail@example.com' but typoscript configuration is incomplete. Please add : \Typoheads\Formhandler\Finisher\Mail)

It seems, `getPreparedClassName` returns an classname without left slash, but the comparison expects a slash.

**Comment by reinhardfuehricht** [comment]
Are you sure you are using the current master? I just tested it and got no such problem.

The comparison uses "prepareClassName" for the static part and "getPreparedClassName" for getting the class name set in TypoScript. This method internally uses "prepareClassName" too, so the values should be equally processed resulting in a class name without leading backslash.

**Comment by pserrer** [comment]
You're right - the current release fixed this issue
